- README.md
Don't want the hassle of maintaining the dev branch for such little benefit
> fix: Updated contributing branch name

- pages/index.tsx
> fix: Adds domain to the mobile dropdown

- package-lock.json
- package.json
Too much hassle faster to do it by hand tbh. Testing release notes thing
> chore: Removed commitizen

- .github/release-drafter.yml
- README.md
If this guideline is followed, hopefully 🤞 changelogs will be generated automatically
> docs: Added contribution guidelines for PR titles

- .github/semantic.yml
- .github/workflows/deploy.yml
- .github/workflows/tests.yml
- commitlint.config.js
- package-lock.json
- package.json
Pretty sure this will break. Let's see
> tests: Added pull requests on PR / Merge on main & dev

- .env.sample
- .github/workflows/deploy.yml
- .github/workflows/tests.yml
- package-lock.json
- package.json
- tests/users.test.ts
- types.d.ts
- utils/passwords.ts
- utils/users/createUser.ts
- utils/users/getUserByEmail.ts
Just do a search for `argon2 lambda` and there are a ton of issues which I don't really want to deal with right now. Bcrypt is fine.
> fix: Removed argon2 and added basic get user by email function

- pages/api/users/email/index.ts
- pages/api/users/index.ts
- tests/users.test.ts
- utils/clean.ts
- utils/users/createUser.ts
I don't really want emails in query strings so. Might revisit this later
> feat: Added retrieval of user by email

- .github/workflows/deploy.yml
> fix: Added correct branch name for deploying

- pages/api/funnels/[funnel_id]/stages/index.ts
- pages/api/funnels/index.ts
- pages/api/orgs/index.ts
#77 
Also users cannot create an org with the name of `NO_ORG_ASSIGNED`
> fix: Org is needed to create funnels and stages

- pages/api/orgs/[org_id]/invite.ts
- utils/invites/createOrgInvite.ts
> chore: Block multiple invites from being sent to a user for the same org

- package-lock.json
- package.json
- pages/api/openings/[opening_id]/index.ts
- pages/openings/[opening_id]/stages/index.tsx
- types.d.ts
- utils/openings/removeStageFromOpening.ts
- utils/openings/reorderStagesInOpening.ts
- utils/stages/deleteStage.ts
- utils/stages/getAllStagesInOpening.ts
> feat: Change the order of stages in an opening

- components/Navbar/SignedInNav.tsx
I hate that stupid little dropdown. So stupid. Ugh. Going to regret this i know it.
> fix: Added client side routing to profile link dropdown

- SWR/useApplicantById.ts
- components/Applicants/ApplicantList.tsx
- components/Applicants/ApplicantProfileModal.tsx
- components/Applicants/CustomEditableInput.tsx
- components/Applicants/CustomEditableSave.tsx
- components/Navbar/NavbarSearch.tsx
- components/Openings/DropDown.tsx
- components/Openings/OpeningsList.tsx
- package-lock.json
- package.json
- pages/api/applicants/[applicant_id]/index.ts
- pages/openings/[opening_id]/stages/[stage_id]/applicants.tsx
- types.d.ts
- utils/applicants/updateApplicant.ts
https://user-images.githubusercontent.com/22891173/135896633-95a54c3e-3efc-4590-b05e-04a34ffb4165.mov
> feat: You can edit applicants now

- pages/api/auth/login.ts
- utils/time.ts
Fixes #325
Time.past was adding time instead of subtracting :$
> fix: Users being able to spam login links (bug with Time wrapper)

- bin/plutomi.ts
- lib/DynamoDBStack.ts
Also removed capacity as default billing mode is on demand
> feat: Added DynamoDB to the deployment stack 

- pages/faq.tsx
Hi I have moved the login component as asked.
> fix: moved the login component below the FAQs

- newMiddleware.ts
> fix: return messages for middleware

- axios.ts
- next.config.js
> 🐛 fix: API URL on the frontend set to localhost

- README.md
> docs: Removed emojis from docs

- Controllers/Openings.ts
- Controllers/Orgs.ts
- Controllers/Stages.ts
- app.ts
- models/Stages/deleteStage.ts
- models/Users/getUserById.ts
> fix: Wrong dynamo table being used on users, misc errors when deleting an org & opening

- Adapters/ApplicantsService.ts
- Adapters/OpeningsService.ts
- Adapters/QuestionsService.ts
- Adapters/StagesService.ts
- Adapters/UsersService.ts
- Controllers/Applicants.ts
- Controllers/Emails.ts
- Controllers/Openings.ts
- Controllers/Orgs.ts
- Controllers/Questions.ts
- Controllers/Stages.ts
- Controllers/Users.ts
- components/Stages/StageCard.tsx
- models/Applicants/updateApplicant.ts
- models/Openings/updateOpening.ts
- models/Questions/updateQuestion.ts
- models/Stages/updateStage.ts
- models/Users/updateUser.ts
- types/main.d.ts
> chore: Renamed newXValues with just newValues

- Controllers/Invites/create-invites.ts
- models/Invites/create-invite.ts
- types/dynamo.d.ts
- types/main.d.ts
> chore: Removed unnecessary data from recipient when creating invites

- Config.ts
- Controllers/Invites/create-invites.ts
- adapters/Invites.ts
- components/CreateInviteModal.tsx
- components/Stages/StagesSettingsContent.tsx
- components/Team/PendingInviteCard.tsx
- components/Team/TeamContent.tsx
- tests/invites.test.ts
- tests/orgs.test.ts
> feat: Users can set how long invites last for

- Controllers/Auth/login.ts
- Controllers/Users/index.ts
- Controllers/Users/remove-user-from-org.ts
- adapters/Users.ts
- app.ts
- components/CreateInviteModal.tsx
- components/Team/UserCard.tsx
- models/Orgs/create-and-join-org.ts
- models/Users/index.ts
- models/Users/remove-user-from-org.ts
- tests/orgs.test.ts
- types/dynamo.d.ts
> feat: Org admins can remove users from their org

- Controllers/PublicInfo/getOpeningsInOrg.ts
- components/PublicOpeningListItem/PublicOpeningListItem.tsx
> fix: Undefined orgId on applicants page, closes #631

- Controllers/PublicInfo/getOpening.ts
- README.md
- app.ts
- components/CreateInviteModal/CreateInviteModal.tsx
- middleware/withCleanWebhookId.ts
- models/Webhooks/createWebhook.ts
Closes #645
Closes #642 
Closes #637
Closes #643
@mazupicua
> Various bugfixes

- Controllers/Auth/requestLoginLink.ts
cc @cosmin-harangus :)
Closes #658
> Fix new users not being able to log in

- Config.ts
- Controllers/Auth/login.ts
- Controllers/Auth/requestLoginLink.ts
- middleware/withHasOrg.ts
> fix: Login links .env

- routes/openings.ts
> fix: Delete stage using wrong API route after refactor

- components/Login/Login.tsx
- components/LoginHomepage/LoginHomepage.tsx
> Reset request login link button state on errors

- lib/CommsMachineStack.ts
- lib/DeleteChildrenMachineStack.ts
> Refactored state machines to use top-level properties

- Controllers/Invites/createInvite.ts
- components/DashboardPageContent/DashboardPageContent.tsx
- components/TeamPageContent/TeamPageContent.tsx
- package-lock.json
- pages/_app.tsx
- utils/emailIsTheSame.ts
- utils/nameIsDefault.ts
> Require name to be updated from default before sending emails

- .github/workflows/deploy.yml
> Added `NEXT_PUBLIC_WEBSITE_URL` to deploy vars 

- functions/utils/getLambdaConfig.ts
- lib/DeleteChildrenMachineStack.ts
- lib/StreamProcessorStack.ts
- lib/WebhooksMachineStack.ts
- pages/index.tsx
Fixing a deployment issue with mikro orm and esbuild
> Added lamda config for Mikro-Orm

- functions/stream-processor.ts
- functions/utils/getLambdaConfig.ts
- lib/DeleteChildrenMachineStack.ts
> Fixing lambda file imports in `getLambdaConfig()`

- .eslintrc.json
- .github/workflows/linter.yml
- README.md
- packages/api/env.ts
- plutomi.code-workspace
> Linter GitHub Action

- README.md
> Adding badges for actions, updated contributors

- packages/api/package.json
> Fixing an issue with infinite restarts in `dev`

- packages/web/components/LatestCommits/Commit.tsx
- packages/web/components/WaitListCard/WaitListCard.tsx
- packages/web/pages/index.tsx
Dependabots long ass commits keep breaking the styling on these 
https://github.com/plutomi/plutomi/pull/886
> Truncating commit length on homepage, removing dependabot 

- packages/api/.eslintrc.json
- packages/api/package.json
- packages/api/utils/emails/index.ts
- packages/infra/utils/createSesConfig.ts
- yarn.lock
> Added a few more eslint rules

- packages/api/.env.sample
- packages/api/Cargo.lock
- packages/api/Cargo.toml
- packages/api/Dockerfile
- packages/api/src/controllers.rs
- packages/api/src/controllers/sample.rs
- packages/api/src/utils/log_req_res.rs
- packages/api/src/utils/logger.rs
- packages/aws/lib/createFargateService.ts
- packages/aws/lib/createTaskDefinition.ts
- packages/aws/utils/env.ts
> Fixing `openssl` and `env` issue, shrinking image size

- README.md
- packages/aws/.env.sample
- packages/aws/bin/plutomi.ts
- scripts/deploy.sh
Split .env up, added checks and colors 
Closes #926
> 926 - Enforce deployment env to match local `.env`
